[2023-08-13 12:49:44,997] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: submit_pyspark_script_to_emr.execute_pyspark_script manual__2023-08-13T12:49:39.412404+00:00 [queued]>
[2023-08-13 12:49:45,023] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: submit_pyspark_script_to_emr.execute_pyspark_script manual__2023-08-13T12:49:39.412404+00:00 [queued]>
[2023-08-13 12:49:45,024] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-13 12:49:45,025] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-08-13 12:49:45,026] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-13 12:49:45,048] {taskinstance.py:1377} INFO - Executing <Task(EmrAddStepsOperator): execute_pyspark_script> on 2023-08-13 12:49:39.412404+00:00
[2023-08-13 12:49:45,055] {standard_task_runner.py:52} INFO - Started process 207 to run task
[2023-08-13 12:49:45,060] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'submit_pyspark_script_to_emr', 'execute_pyspark_script', 'manual__2023-08-13T12:49:39.412404+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/orchestration/submit_spark_job_to_emr.py', '--cfg-path', '/tmp/tmpyq10rbnm', '--error-file', '/tmp/tmphupn26_u']
[2023-08-13 12:49:45,063] {standard_task_runner.py:80} INFO - Job 68: Subtask execute_pyspark_script
[2023-08-13 12:49:45,184] {task_command.py:370} INFO - Running <TaskInstance: submit_pyspark_script_to_emr.execute_pyspark_script manual__2023-08-13T12:49:39.412404+00:00 [running]> on host airflow_scheduler
[2023-08-13 12:49:45,476] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=submit_pyspark_script_to_emr
AIRFLOW_CTX_TASK_ID=execute_pyspark_script
AIRFLOW_CTX_EXECUTION_DATE=2023-08-13T12:49:39.412404+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-13T12:49:39.412404+00:00
[2023-08-13 12:49:45,503] {base.py:68} INFO - Using connection ID 'aws_default' for task execution.
[2023-08-13 12:49:45,508] {base_aws.py:210} INFO - Credentials retrieved from extra_config
[2023-08-13 12:49:45,509] {base_aws.py:100} INFO - Retrieving region_name from Connection.extra_config['region_name']
[2023-08-13 12:49:45,621] {emr.py:104} INFO - Adding steps to j-1Z3BJELOTWETV
[2023-08-13 12:49:45,625] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/operators/emr.py", line 112, in execute
    response = emr.add_job_flow_steps(JobFlowId=job_flow_id, Steps=steps)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 875, in _make_api_call
    api_params, operation_model, context=request_context
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 936, in _convert_to_request_dict
    api_params, operation_model
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter Steps[0].HadoopJarStep.Args[77], value: 9, type: <class 'int'>, valid types: <class 'str'>
[2023-08-13 12:49:45,649] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=submit_pyspark_script_to_emr, task_id=execute_pyspark_script, execution_date=20230813T124939, start_date=20230813T124945, end_date=20230813T124945
[2023-08-13 12:49:45,737] {standard_task_runner.py:97} ERROR - Failed to execute job 68 for task execute_pyspark_script (Parameter validation failed:
Invalid type for parameter Steps[0].HadoopJarStep.Args[77], value: 9, type: <class 'int'>, valid types: <class 'str'>; 207)
[2023-08-13 12:49:45,803] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-08-13 12:49:45,871] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
